USE MASTER
GO

IF EXISTS(SELECT * FROM sys.databases WHERE name='ToyStore')
BEGIN
    DROP DATABASE ToyStore;
END

CREATE DATABASE ToyStore
GO

USE ToyStore
GO

CREATE TABLE tblTheLoai
(
    MaTL  NVARCHAR(50)  PRIMARY KEY,
    TenTL NVARCHAR(100) NOT NULL DEFAULT N'Chưa đặt tên',
	MoTa  NVARCHAR(500)
)	
GO

CREATE TABLE tblDoChoi
(
    MaDC NVARCHAR(50) PRIMARY KEY,
    TenDC NVARCHAR(100) NOT NULL DEFAULT N'Chưa đặt tên',
    MaTL NVARCHAR(50) NOT NULL,
    GiaBan FLOAT NOT NULL DEFAULT 0,
	GiaNhap FLOAT NULL DEFAULT 0,
    SoLuong INT NOT NULL DEFAULT 0,
	Anh		NVARCHAR(200) NULL,
	GhiChu NVARCHAR(200) NULL,
    
    FOREIGN KEY (MaTL) REFERENCES dbo.tblTheLoai(MaTL)
)
GO

CREATE TABLE tblKhachHang
(
    MaKH NVARCHAR(50) PRIMARY KEY,
    TenKH NVARCHAR(100) NOT NULL DEFAULT N'Chưa đặt tên',
    SDT NVARCHAR(20) NOT NULL DEFAULT '',
    DiaChi NVARCHAR(200) NOT NULL DEFAULT '',
	Email 	NVARCHAR(200) NULL
)
GO

CREATE TABLE tblNhanVien
(
	MaNV			NVARCHAR(50) PRIMARY KEY,
	TenNV			NVARCHAR(100) NOT NULL DEFAULT N'Chưa đặt tên',
	GioiTinh		BIT							,
	NgaySinh		DATETIME					,
	HinhDD			NVARCHAR(MAX)				,
	SDT				VARCHAR(50)					,
	DiaChi			NVARCHAR(50)				,
	TenDangNhap		VARCHAR(50)			UNIQUE	,
	MatKhau			VARCHAR(max)		NOT NULL,
)
GO

CREATE TABLE tblHoaDon
(
    MaHD NVARCHAR(50) PRIMARY KEY,
	MaNV NVARCHAR(50) NOT NULL,
    MaKH NVARCHAR(50) NOT NULL,
	NgayLap DATE	  NOT NULL,	
    TongTien FLOAT NOT NULL DEFAULT 0,
    TrangThai INT NOT NULL DEFAULT 0, -- 0: Chưa xử lý, 1: Đã xử lý, 2: Đã hủy
    
    FOREIGN KEY (MaKH) REFERENCES dbo.tblKhachHang(MaKH),
	FOREIGN KEY (MaNV) REFERENCES dbo.tblNhanVien(MaNV)
)
GO

CREATE TABLE tblChiTietHoaDon
(
    MaHD NVARCHAR(50) NOT NULL,
    MaDC NVARCHAR(50) NOT NULL,
    SoLuong INT NOT NULL DEFAULT 0,
    GiaBan FLOAT NOT NULL DEFAULT 0,
	GiamGia INT NOT NULL DEFAULT 0,
    TongTien FLOAT NOT NULL DEFAULT 0,
	PRIMARY KEY CLUSTERED (MaHD ASC, MaDC ASC),
    FOREIGN KEY (MaHD) REFERENCES dbo.tblHoaDon(MaHD),
    FOREIGN KEY (MaDC) REFERENCES dbo.tblDoChoi(MaDC)
)
GO

USE ToyStore
GO

INSERT INTO tblTheLoai 
VALUES (N'L01',N'Lego',N'Do choi lap rap')
GO 


INSERT INTO tblDoChoi 
VALUES (N'DC01',N'Lego NINJA GO RED',N'L01',250000,200000,100,N'Chua co hinh',N'Do choi')
GO